services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - quiz-network

  web:
    image: nginx:alpine
    container_name: quiz-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - quiz-network

  db:
    image: mysql:5.7
    container_name: quiz-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge

volumes:
  mysql-data: